//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMef730.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/", ConfigurationName="ServiceReference1.RicevutaPdf730")]
    public interface RicevutaPdf730 {
        
        // CODEGEN: Il parametro 'DatiOutputRichiesta' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DatiOutputRichiesta")]
        WinMef730.ServiceReference1.RicevutaPdfResponse RicevutaPdf(WinMef730.ServiceReference1.RicevutaPdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WinMef730.ServiceReference1.RicevutaPdfResponse> RicevutaPdfAsync(WinMef730.ServiceReference1.RicevutaPdfRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/")]
    public partial class datiInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pinCodeField;
        
        private string protocolloField;
        
        private string opzionale1Field;
        
        private string opzionale2Field;
        
        private string opzionale3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pinCode {
            get {
                return this.pinCodeField;
            }
            set {
                this.pinCodeField = value;
                this.RaisePropertyChanged("pinCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string protocollo {
            get {
                return this.protocolloField;
            }
            set {
                this.protocolloField = value;
                this.RaisePropertyChanged("protocollo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string opzionale1 {
            get {
                return this.opzionale1Field;
            }
            set {
                this.opzionale1Field = value;
                this.RaisePropertyChanged("opzionale1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string opzionale2 {
            get {
                return this.opzionale2Field;
            }
            set {
                this.opzionale2Field = value;
                this.RaisePropertyChanged("opzionale2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string opzionale3 {
            get {
                return this.opzionale3Field;
            }
            set {
                this.opzionale3Field = value;
                this.RaisePropertyChanged("opzionale3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/")]
    public partial class dettaglioEsitoNegativo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codiceField;
        
        private string descrizioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("codice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("descrizione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/")]
    public partial class dettaglioEsitoPositivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] pdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("pdf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/")]
    public partial class esitiPositivi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dettaglioEsitoPositivo dettagliEsitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dettaglioEsitoPositivo dettagliEsito {
            get {
                return this.dettagliEsitoField;
            }
            set {
                this.dettagliEsitoField = value;
                this.RaisePropertyChanged("dettagliEsito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/")]
    public partial class datiOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string esitoChiamataField;
        
        private esitiPositivi esitiPositiviField;
        
        private dettaglioEsitoNegativo[] esitiNegativiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string esitoChiamata {
            get {
                return this.esitoChiamataField;
            }
            set {
                this.esitoChiamataField = value;
                this.RaisePropertyChanged("esitoChiamata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public esitiPositivi esitiPositivi {
            get {
                return this.esitiPositiviField;
            }
            set {
                this.esitiPositiviField = value;
                this.RaisePropertyChanged("esitiPositivi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public dettaglioEsitoNegativo[] esitiNegativi {
            get {
                return this.esitiNegativiField;
            }
            set {
                this.esitiNegativiField = value;
                this.RaisePropertyChanged("esitiNegativi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicevutaPdf", WrapperNamespace="http://ricevutapdf.p730.sanita.sogei.it/", IsWrapped=true)]
    public partial class RicevutaPdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WinMef730.ServiceReference1.datiInput DatiInputRichiesta;
        
        public RicevutaPdfRequest() {
        }
        
        public RicevutaPdfRequest(WinMef730.ServiceReference1.datiInput DatiInputRichiesta) {
            this.DatiInputRichiesta = DatiInputRichiesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicevutaPdfResponse", WrapperNamespace="http://ricevutapdf.p730.sanita.sogei.it/", IsWrapped=true)]
    public partial class RicevutaPdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ricevutapdf.p730.sanita.sogei.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WinMef730.ServiceReference1.datiOutput DatiOutputRichiesta;
        
        public RicevutaPdfResponse() {
        }
        
        public RicevutaPdfResponse(WinMef730.ServiceReference1.datiOutput DatiOutputRichiesta) {
            this.DatiOutputRichiesta = DatiOutputRichiesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RicevutaPdf730Channel : WinMef730.ServiceReference1.RicevutaPdf730, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RicevutaPdf730Client : System.ServiceModel.ClientBase<WinMef730.ServiceReference1.RicevutaPdf730>, WinMef730.ServiceReference1.RicevutaPdf730 {
        
        public RicevutaPdf730Client() {
        }
        
        public RicevutaPdf730Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RicevutaPdf730Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RicevutaPdf730Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RicevutaPdf730Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinMef730.ServiceReference1.RicevutaPdfResponse WinMef730.ServiceReference1.RicevutaPdf730.RicevutaPdf(WinMef730.ServiceReference1.RicevutaPdfRequest request) {
            return base.Channel.RicevutaPdf(request);
        }
        
        public WinMef730.ServiceReference1.datiOutput RicevutaPdf(WinMef730.ServiceReference1.datiInput DatiInputRichiesta) {
            WinMef730.ServiceReference1.RicevutaPdfRequest inValue = new WinMef730.ServiceReference1.RicevutaPdfRequest();
            inValue.DatiInputRichiesta = DatiInputRichiesta;
            WinMef730.ServiceReference1.RicevutaPdfResponse retVal = ((WinMef730.ServiceReference1.RicevutaPdf730)(this)).RicevutaPdf(inValue);
            return retVal.DatiOutputRichiesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinMef730.ServiceReference1.RicevutaPdfResponse> WinMef730.ServiceReference1.RicevutaPdf730.RicevutaPdfAsync(WinMef730.ServiceReference1.RicevutaPdfRequest request) {
            return base.Channel.RicevutaPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinMef730.ServiceReference1.RicevutaPdfResponse> RicevutaPdfAsync(WinMef730.ServiceReference1.datiInput DatiInputRichiesta) {
            WinMef730.ServiceReference1.RicevutaPdfRequest inValue = new WinMef730.ServiceReference1.RicevutaPdfRequest();
            inValue.DatiInputRichiesta = DatiInputRichiesta;
            return ((WinMef730.ServiceReference1.RicevutaPdf730)(this)).RicevutaPdfAsync(inValue);
        }
    }
}
